const products = [
  {id:1,name:'Daily Defense SPF 50',category:'Skincare',type:'Mineral sunscreen',price:24,oldPrice:null,badge:'Bestseller',image:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=700&q=80'},
  {id:2,name:'Calm + Restore Cream',category:'Skincare',type:'Barrier repair',price:28,oldPrice:null,badge:'New',image:'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=700&q=80'},
  {id:3,name:'Essential Pain Relief',category:'Medicine',type:'Paracetamol 500mg',price:8,oldPrice:null,badge:null,image:'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=700&q=80'},
  {id:4,name:'Glow From Within',category:'Wellness',type:'Daily vitamin complex',price:19,oldPrice:24,badge:'Save 20%',image:'https://images.unsplash.com/photo-1550572017-edd951aa8ca0?auto=format&fit=crop&w=700&q=80'},
  {id:5,name:'Hydra Lip Treatment',category:'Skincare',type:'Overnight balm',price:14,oldPrice:null,badge:null,image:'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=700&q=80'},
  {id:6,name:'Magnesium Night',category:'Wellness',type:'Gentle sleep support',price:16,oldPrice:null,badge:null,image:'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=700&q=80'},
  {id:7,name:'First Aid Essentials',category:'Medicine',type:'12 piece care kit',price:21,oldPrice:null,badge:'Everyday',image:'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=700&q=80'},
  {id:8,name:'Silk Body Wash',category:'Skincare',type:'Fragrance-free',price:18,oldPrice:null,badge:null,image:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=700&q=80'}
];
let activeCategory='All';
let featuredOnly=false;
let cart=JSON.parse(localStorage.getItem('kashmir-cures-cart')||'[]');
const grid=document.getElementById('productGrid');
const cartDrawer=document.getElementById('cartDrawer');
const overlay=document.getElementById('drawerOverlay');
const toast=document.getElementById('toast');
const checkoutPage=document.getElementById('checkoutPage');
function money(value){return `₹${value.toFixed(2)}`}
function renderProducts(){
  const filtered=products.filter(product=>(activeCategory==='All'||product.category===activeCategory)&&(!featuredOnly||product.badge));
  grid.innerHTML=filtered.map(product=>`<article class="product-card"><div class="product-image"><img src="${product.image}" alt="${product.name}" loading="lazy"/>${product.badge?`<span class="badge">${product.badge}</span>`:''}<button class="quick-add" data-add="${product.id}" aria-label="Add ${product.name} to bag"><i data-lucide="plus"></i></button></div><div class="product-info"><h3>${product.name}</h3><div class="product-meta"><span>${product.type}</span><span class="price">${money(product.price)}${product.oldPrice?` <s>${money(product.oldPrice)}</s>`:''}</span></div></div></article>`).join('');
  grid.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>addToCart(Number(button.dataset.add))));
  lucide.createIcons();
}
function addToCart(id){const existing=cart.find(item=>item.id===id); if(existing) existing.qty+=1; else cart.push({id,qty:1}); persist(); renderCart(); showToast();}
function changeQty(id,delta){const item=cart.find(row=>row.id===id);if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(row=>row.id!==id);persist();renderCart();}
function persist(){localStorage.setItem('kashmir-cures-cart',JSON.stringify(cart));document.getElementById('cartCount').textContent=cart.reduce((sum,item)=>sum+item.qty,0)}
function renderCart(){const items=document.getElementById('cartItems');const empty=document.getElementById('cartEmpty');const footer=document.getElementById('cartFooter');if(!cart.length){items.innerHTML='';empty.classList.add('show');footer.style.display='none';return}empty.classList.remove('show');footer.style.display='block';items.innerHTML=cart.map(item=>{const product=products.find(row=>row.id===item.id);return `<div class="cart-row"><img src="${product.image}" alt="${product.name}"/><div class="cart-row-info"><strong>${product.name}</strong><small>${product.type}</small><div class="row-bottom"><div class="qty-control"><button data-qty="${product.id}" data-delta="-1">-</button><span>${item.qty}</span><button data-qty="${product.id}" data-delta="1">+</button></div><strong>${money(product.price*item.qty)}</strong></div></div></div>`}).join('');items.querySelectorAll('[data-qty]').forEach(button=>button.addEventListener('click',()=>changeQty(Number(button.dataset.qty),Number(button.dataset.delta))));document.getElementById('cartTotal').textContent=money(cart.reduce((sum,item)=>{const product=products.find(row=>row.id===item.id);return sum+product.price*item.qty},0));}
function cartTotal(){return cart.reduce((sum,item)=>{const product=products.find(row=>row.id===item.id);return sum+product.price*item.qty},0)}
function renderCheckout(){const total=cartTotal();document.getElementById('placeOrderTotal').textContent=money(total);document.getElementById('summarySubtotal').textContent=money(total);document.getElementById('summaryTotal').textContent=money(total);document.getElementById('summaryItems').innerHTML=cart.map(item=>{const product=products.find(row=>row.id===item.id);return `<div class="summary-item"><img src="${product.image}" alt="${product.name}"/><div><strong>${product.name}</strong><span>Qty ${item.qty} · ${product.type}</span></div><b>${money(product.price*item.qty)}</b></div>`}).join('');lucide.createIcons()}
function openCart(){cartDrawer.classList.add('open');overlay.classList.add('open');document.body.style.overflow='hidden'}
function closeCart(){cartDrawer.classList.remove('open');overlay.classList.remove('open');document.body.style.overflow=''}
function openCheckout(){if(!cart.length)return;closeCart();renderCheckout();checkoutPage.hidden=false;document.body.classList.add('checkout-open');window.scrollTo({top:0,behavior:'smooth'})}
function closeCheckout(){checkoutPage.hidden=true;document.body.classList.remove('checkout-open');window.scrollTo({top:0,behavior:'smooth'})}
let toastTimer;function showToast(){toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelector('.tab.active').classList.remove('active');tab.classList.add('active');activeCategory=tab.dataset.category;renderProducts()}));
document.getElementById('filterButton').addEventListener('click',()=>{featuredOnly=!featuredOnly;document.getElementById('filterButton').innerHTML=featuredOnly?'<i data-lucide="x"></i> Clear filter':'<i data-lucide="sliders-horizontal"></i> Filter';renderProducts()});
document.getElementById('cartButton').addEventListener('click',openCart);document.getElementById('closeCart').addEventListener('click',closeCart);overlay.addEventListener('click',closeCart);document.getElementById('checkoutButton').addEventListener('click',openCheckout);document.getElementById('backToShop').addEventListener('click',closeCheckout);document.getElementById('editBag').addEventListener('click',()=>{closeCheckout();openCart()});
document.querySelectorAll('.payment-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelector('.payment-tab.active').classList.remove('active');tab.classList.add('active');document.querySelectorAll('.payment-panel').forEach(panel=>panel.hidden=true);document.getElementById(`${tab.dataset.payment}Panel`).hidden=false;document.querySelectorAll('.payment-panel [required]').forEach(input=>input.required=tab.dataset.payment==='card')}));
const prescriptionInput=document.getElementById('prescriptionInput');
const prescriptionPreviews=document.getElementById('prescriptionPreviews');
let prescriptionFiles=[];
function renderPrescriptionPreviews(){prescriptionPreviews.innerHTML=prescriptionFiles.map((file,index)=>`<div class="prescription-preview"><img src="${URL.createObjectURL(file)}" alt="Prescription image ${index+1}"/><button type="button" data-remove-prescription="${index}" aria-label="Remove prescription image ${index+1}"><i data-lucide="x"></i></button></div>`).join('');prescriptionPreviews.querySelectorAll('[data-remove-prescription]').forEach(button=>button.addEventListener('click',()=>{prescriptionFiles.splice(Number(button.dataset.removePrescription),1);renderPrescriptionPreviews()}));lucide.createIcons()}
prescriptionInput.addEventListener('change',event=>{const selected=[...event.target.files].filter(file=>file.type.startsWith('image/'));prescriptionFiles=[...prescriptionFiles,...selected].slice(0,5);event.target.value='';renderPrescriptionPreviews()});
function renderOrderConfirmation(form){const orderId=`KC-${Date.now().toString().slice(-6)}`;const customerName=`${form.elements.firstName.value} ${form.elements.lastName.value}`.trim();const address=`${form.elements.address.value}, ${form.elements.city.value}, ${form.elements.state.value} ${form.elements.pin.value}`;const orderedItems=cart.map(item=>{const product=products.find(row=>row.id===item.id);return `<div class="confirmation-item"><img src="${product.image}" alt="${product.name}"/><div><strong>${product.name}</strong><span>Qty ${item.qty} · ${product.type}</span></div><b>${money(product.price*item.qty)}</b></div>`}).join('');const total=cartTotal();checkoutPage.innerHTML=`<div class="confirmation-shell"><div class="confirmation-header"><div><span class="success-icon"><i data-lucide="check"></i></span><p class="eyebrow">Order confirmed</p><h1>Care is on<br /><em>its way.</em></h1><p>Thank you, ${customerName || 'there'}. We have received your order and will send updates to ${form.elements.email.value}.</p><strong class="order-number">Order ${orderId}</strong></div><div class="delivery-card"><div class="delivery-card-top"><span class="status-dot"></span><div><strong>Preparing your order</strong><span>Estimated delivery · 2-3 business days</span></div></div><div class="status-track"><div class="status-step active"><span><i data-lucide="check"></i></span><div><strong>Order confirmed</strong><small>Just now</small></div></div><div class="status-step"><span><i data-lucide="package"></i></span><div><strong>Being prepared</strong><small>Next up</small></div></div><div class="status-step"><span><i data-lucide="truck"></i></span><div><strong>On its way</strong><small>We'll notify you</small></div></div></div></div></div><div class="confirmation-grid"><section class="confirmation-panel"><div class="confirmation-panel-heading"><div><p class="eyebrow">Your purchase</p><h2>Order summary</h2></div><span class="confirmed-label">Paid securely</span></div>${orderedItems}<div class="confirmation-total"><span>Total paid</span><strong>${money(total)}</strong></div></section><aside class="confirmation-panel delivery-details"><p class="eyebrow">Delivery details</p><h2>Arriving at</h2><strong>${customerName}</strong><p>${address}</p><p>${form.elements.phone.value}</p><div class="detail-note"><i data-lucide="shield-check"></i><span>Discreet packaging is included with every Kashmir Cures order.</span></div></aside></div><button class="primary-button confirmation-button" id="successBack">Continue shopping <i data-lucide="arrow-right"></i></button></div>`;cart=[];persist();lucide.createIcons();document.getElementById('successBack').addEventListener('click',closeCheckout)}
document.getElementById('checkoutForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.checkValidity()){form.reportValidity();return}renderOrderConfirmation(form)});
document.getElementById('searchButton').addEventListener('click',()=>{const query=window.prompt('Search Kashmir Cures products');if(!query)return;const match=products.filter(product=>`${product.name} ${product.type} ${product.category}`.toLowerCase().includes(query.toLowerCase()));grid.innerHTML=match.length?match.map(product=>`<article class="product-card"><div class="product-image"><img src="${product.image}" alt="${product.name}"/><button class="quick-add" data-add="${product.id}" aria-label="Add ${product.name} to bag"><i data-lucide="plus"></i></button></div><div class="product-info"><h3>${product.name}</h3><div class="product-meta"><span>${product.type}</span><span class="price">${money(product.price)}</span></div></div></article>`).join(''):`<p style="grid-column:1/-1;color:#6d7f79;padding:30px 0">No products found for “${query}”. Try another search.</p>`;grid.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>addToCart(Number(button.dataset.add))));lucide.createIcons()});
renderProducts();persist();renderCart();lucide.createIcons();
